language: node_js

node_js:
  - 'lts/*'

cache: npm

branches:
  only:
    - master

script:
  - npm run check-types
  - npm test -- --coverage

after_success:
  - npx codecov -f coverage/lcov.info

notifications:
  email:
    on_success: change
    on_failure: always
